{{- if .Values.postgres.create }}
apiVersion: v1
kind: Service
metadata:
  name: ov-watcher-postgres
  labels:
    app: ov-watcher-postgres
spec:
  clusterIP: None
  selector:
    app: ov-watcher-postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ov-watcher-postgres
  labels:
    app: ov-watcher-postgres
spec:
  serviceName: ov-watcher-postgres
  replicas: 1
  selector:
    matchLabels:
      app: ov-watcher-postgres
  template:
    metadata:
      labels:
        app: ov-watcher-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ov
            - name: POSTGRES_DB
              value: ov
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ov-watcher-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
{{- end }}
