{{- if .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ov-watcher-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
{{- end }}
