apiVersion: v1
kind: Secret
metadata:
  name: ov-watcher-secret
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: "{{ .Values.secrets.telegramBotToken }}"
  TELEGRAM_CHAT_ID: "{{ .Values.secrets.telegramChatId }}"
